# Generated by Django 4.1.2 on 2022-10-17 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredmembermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registeredmembermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registeredmembermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registeredmembermodel',
            name='user_name',
        ),
        migrations.AddField(
            model_name='registeredmembermodel',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeredmembermodel',
            name='account_state',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'CLOSED'), (2, 'CANCELED'), (3, 'BLACKLISTED'), (4, 'BLOCKED')], default=0),
        ),
    ]
