# Generated by Django 4.1.2 on 2022-10-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_textphotobasedentitymodel_delete_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textphotobasedentitymodel',
            name='membersWhoDownvoted',
            field=models.ManyToManyField(related_name='upvote', to='backend.registeredmembermodel', verbose_name='Downvoting members'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='membersWhoUpvoted',
            field=models.ManyToManyField(related_name='Downvote', to='backend.registeredmembermodel', verbose_name='Upvoting members'),
        ),
    ]
