# Generated by Django 4.1.2 on 2022-10-17 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_textphotobasedentitymodel_memberswhodownvoted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_problem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.answermodel', verbose_name='answers list')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.commentmodel', verbose_name='comments list')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.textphotobasedentitymodel')),
                ('tags', models.ManyToManyField(related_name='tags', to='backend.tags', verbose_name='tags list')),
            ],
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.textphotobasedentitymodel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.commentmodel', verbose_name='comments list'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.textphotobasedentitymodel'),
        ),
    ]
