# Generated by Django 4.1.2 on 2022-10-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_answermodel_commentmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='creator',
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.answermodel', verbose_name='answers list'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.commentmodel', verbose_name='comments list'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags', to='backend.tags', verbose_name='tags list'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='membersWhoDownvoted',
            field=models.ManyToManyField(null=True, related_name='upvote', to='backend.registeredmembermodel', verbose_name='Downvoting members'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='membersWhoUpvoted',
            field=models.ManyToManyField(null=True, related_name='Downvote', to='backend.registeredmembermodel', verbose_name='Upvoting members'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='photos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.photos', verbose_name='List of photos'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSED'), (2, 'DELETED'), (3, 'DEFAULT')], default=3),
        ),
    ]
