# Generated by Django 4.1.2 on 2022-10-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_photos_creator_alter_questionmodel_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='backend.tags', verbose_name='tags list'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='membersWhoDownvoted',
            field=models.ManyToManyField(related_name='upvote', to='backend.registeredmembermodel', verbose_name='Downvoting members'),
        ),
        migrations.AlterField(
            model_name='textphotobasedentitymodel',
            name='membersWhoUpvoted',
            field=models.ManyToManyField(related_name='Downvote', to='backend.registeredmembermodel', verbose_name='Upvoting members'),
        ),
    ]
